workflows:
  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.17.1
      java: 17
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.passtemp"
    
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules -> package-lock.json
        - $CM_BUILD_DIR/android/.gradle -> android/build.gradle
    
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx expo install
      
      - name: Setup Android project
        script: |
          npx expo prebuild -p android --clean
      
      - name: Set up app signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      
      - name: Build Android release
        script: |
          cd android
          ./gradlew bundleRelease
          ./gradlew assembleRelease
    
    artifacts:
      - android/app/build/outputs/bundle/**/*.aab
      - android/app/build/outputs/apk/**/*.apk
    
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-development:
    name: Android Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.17.1
      java: 17
      vars:
        PACKAGE_NAME: "com.passtemp"
    
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules -> package-lock.json
        - $CM_BUILD_DIR/android/.gradle -> android/build.gradle
    
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx expo install
      
      - name: Setup Android project
        script: |
          npx expo prebuild -p android --clean
      
      - name: Build Android debug
        script: |
          cd android
          ./gradlew assembleDebug
    
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
